# PyTorch torch.tensor 编程挑战(答案部分)

## tensor的创建

题目 1：从 Python 列表创建
描述：根据一个一维 Python 列表 [1, 2, 3, 4, 5] 创建一个 PyTorch 张量。

In [1]:
import torch
import numpy as np

In [3]:
l = [1, 2, 3, 4, 5]
t = torch.tensor(l)
print(t)

tensor([1, 2, 3, 4, 5])


题目 2：创建多维张量
描述：根据一个嵌套的 Python 列表 [[1, 2], [3, 4]] 创建一个 2x2 的二维张量。

In [4]:
l = [[1, 2], [3, 4]]
t = torch.tensor(l)
print(l)

[[1, 2], [3, 4]]


题目 3：指定数据类型
描述：创建一个包含 [1.0, 2.0, 3.0] 的张量，并确保其数据类型（dtype）为 torch.float32。

In [5]:
l = [1, 2, 3]
t = torch.tensor(l, dtype=torch.float32)
print(t)

tensor([1., 2., 3.])


题目 4：从 NumPy 数组创建
描述：首先，创建一个包含 [5, 6, 7, 8] 的 NumPy 数组。然后，将这个 NumPy 数组转换为 PyTorch 张量。

In [8]:
n = np.array([5, 6, 7, 8])
t = torch.from_numpy(n)
print(t)

tensor([5, 6, 7, 8])


题目 5：创建需要梯度的张量
描述：创建一个值为 2.0 的标量张量，并设置 requires_grad=True，用于后续的自动求导计算。

In [9]:
t = torch.tensor(2, dtype=torch.float, requires_grad=True)
print(t)

tensor(2., requires_grad=True)


题目 6：使用 clone() 和 detach()
描述：创建一个名为 a 的张量，其值为 [1, 2] 且 requires_grad=True。然后进行以下操作：

创建 b = a.clone()。

创建 c = a.detach()。

请问 b 和 c 的 requires_grad 属性分别是多少？为什么？

In [12]:
a = torch.tensor([1, 2], dtype=float, requires_grad=True)
print(a)
b = a.clone()
print(b)
c = a.detach()
print(c)

print(b.requires_grad)  # True
print(c.requires_grad)  # False

tensor([1., 2.], dtype=torch.float64, requires_grad=True)
tensor([1., 2.], dtype=torch.float64, grad_fn=<CloneBackward0>)
tensor([1., 2.], dtype=torch.float64)
True
False


clone()：复制数据 但保留计算图（requires_grad 状态保持不变）。

detach()：创建一个新的张量，与原计算图断开连接，因此 requires_grad=False。

题目 7：使用工厂函数创建
描述：不直接使用 torch.tensor，而是使用 PyTorch 的工厂函数来完成以下操作：

创建一个形状为 (3, 4) 的全零张量。

创建一个形状为 (2, 5) 的全一张量。

创建一个形状为 (3, 3) 但元素为随机数的张量。

In [14]:
a = torch.zeros([3, 4])
print(a)
b = torch.ones([2, 5])
print(b)
c = torch.rand([3, 3])
print(c)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[0.8270, 0.7475, 0.5623],
        [0.2182, 0.3187, 0.9837],
        [0.0959, 0.9213, 0.1182]])


## 张量的属性与索引

题目 8：获取张量属性
描述：创建一个 3x5 的随机整数张量（范围在0-10之间）。然后打印出这个张量的形状（shape）、数据类型（dtype）和存储设备（device）。

In [15]:
a = torch.rand([3, 5])
print(a.shape)
print(a.dtype)
print(a.device)

torch.Size([3, 5])
torch.float32
cpu


题目 9：基本索引
描述：创建一个 4x4 的二维张量，内容为 [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]。

获取第 2 行，第 3 列的元素（即 7）。

获取整个第 3 行。

获取整个第 2 列。

In [19]:
t = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
print(t[1][2])
print(t[2])
print(t[2, :])
print(t[:, 1]) 

tensor(7)
tensor([[ 9, 10, 11, 12]])
tensor([[5, 6, 7, 8]])


题目 10：切片操作
描述：继续使用上一题的 4x4 张量。

提取出右上角 2x2 的子张量（即 [[3, 4], [7, 8]]）。

提取出所有偶数行（第 0 行和第 2 行）。

